name: test-nodejs-jsdom

on:
  pull_request:
    branches:
      - main

env:
  HEDERAS_CONTRACTS_RELATIVE_PATH: test
  HEDERAS_CONTRACTS_INCLUDED_PREFIXES: general/contracts,general/contracts/import_resolution/node_modules,solidity-by-example/contracts,taskbar/contracts,hedera/contracts

jobs:
  main_test:
    runs-on: ubuntu-latest
    environment: hedera-testnet
    strategy:
      matrix:
        npm_test_script: ["test:node", "test:jsdom"]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install

      - name: Testing
        env:
          HEDERAS_NETWORK: ${{ secrets.HEDERAS_NETWORK }}
          HEDERAS_OPERATOR_ID: ${{ secrets.HEDERAS_OPERATOR_ID }}
          HEDERAS_OPERATOR_KEY: ${{ secrets.HEDERAS_OPERATOR_KEY }}
          HEDERAS_DEFAULT_CONTRACT_REQUESTS_RETURN_ONLY_RECEIPTS: ${{ secrets.HEDERAS_DEFAULT_CONTRACT_REQUESTS_RETURN_ONLY_RECEIPTS }}
        run: npm run ${{ matrix.npm_test_script }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-${{ matrix.npm_test_script }}
          verbose: true
