name: test-manual

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the tests against'
        required: true
        default: main
      environment:
        description: 'Hedera network to run the tests on'
        required: true
        type: environment
        default: hedera-testnet

env:
  HEDERAS_CONTRACTS_RELATIVE_PATH: test
  HEDERAS_CONTRACTS_INCLUDED_PREFIXES: general/contracts,general/contracts/import_resolution/node_modules,solidity-by-example/contracts,taskbar/contracts,hedera/contracts

jobs:
  manual_test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
        npm_test_script: [ 'test:node', 'test:jsdom', 'test:browser' ]    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install

      - name: Testing
        env: 
          HEDERAS_NETWORK: ${{ secrets.HEDERAS_NETWORK }}
          HEDERAS_OPERATOR_ID: ${{ secrets.HEDERAS_OPERATOR_ID }}
          HEDERAS_OPERATOR_KEY: ${{ secrets.HEDERAS_OPERATOR_KEY }}
        run: npm run ${{ matrix.npm_test_script }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-${{ matrix.npm_test_script }}
          verbose: true